-- Summarizing and aggregating numeric data
-- You'll build on functions like min and max to summarize numeric data in new ways. 
-- Add average, variance, correlation, and percentile functions to your toolkit, and learn how to truncate and round numeric values too. 
-- Build complex queries and save your results by creating temporary tables.
