/* Review the missing values by variables within a dataset */
%MACRO MISSING_CHECK(TABLE);

	PROC DATASETS LIB=WORK NOLIST;
	DELETE SUMMARY;
	RUN;

	PROC CONTENTS DATA=&TABLE. OUT=VARIABLES NOPRINT ORDER=VARNUM;
	RUN;

/* Step 2 - Count the number of variables within the model  */
	PROC SQL NOPRINT;
		SELECT COUNT(*) INTO: N FROM VARIABLES;
	QUIT;


	%DO I=1 %TO &N.;
		
		PROC SQL NOPRINT;
			SELECT
				NAME INTO: VARIABLE
			FROM VARIABLES
			WHERE VARNUM=&I.
			;
		QUIT;
		
		DATA TABLE_OUT;
			SET &TABLE. (KEEP=&VARIABLE.);
			VARTYPE=VTYPE(&VARIABLE.);
		RUN;

		PROC SORT DATA=TABLE_OUT NODUPKEY DUPOUT=DUPS OUT=VARTYPE_CHECK;
		BY VARTYPE;
		RUN;

		PROC SQL NOPRINT;
			SELECT
				VARTYPE INTO: VARTYPE
			FROM VARTYPE_CHECK
			;
		QUIT;

		%IF &VARTYPE.=N %THEN %LET MISSING=. ; %ELSE %IF &VARTYPE.=C %THEN %LET MISSING='';
		;
		PROC SQL;
			CREATE TABLE SUMMARY_&I. AS
				SELECT
					"&VARIABLE." AS VARIABLE,
/*					UNIQUE_SYSTEM,*/
					SUM(CASE WHEN &VARIABLE.=&MISSING. THEN 1
					ELSE 0 END) AS MISSING,
					COUNT(*) AS TOTAL,
					SUM(CASE WHEN &VARIABLE.=&MISSING. THEN 1 ELSE 0 END)/COUNT(*) AS MISSING_PCT
				FROM &TABLE.
				;
		QUIT;

		PROC APPEND BASE=SUMMARY DATA=SUMMARY_&I.;
		RUN;

		PROC DATASETS LIB=WORK NOLIST;
		DELETE SUMMARY_&I.;
		RUN;

	%END;

%MEND ;
